### ISSUE TITLE
Error with go generate  (windows 7 64bits)

### ISSUE THREAD

**Issue by adal182** [chai2010/opencv#5]
I have the following Error using TMD-GCC 64bits
![error](https://cloud.githubusercontent.com/assets/10868343/6065575/0c1bddcc-ad2c-11e4-98d0-0a80bddbb6b4.PNG)

**Comment by chai2010** [comment]
@adal182 

Can you try `mingw32-make -f Makefile.windows` (same as run `go generate`)?

And i need more error message, `go version` and `go env`.

Thanks for your feedback.

**Comment by adal182** [comment]
Hi, using the command you suggest i was able to compile all
mingw32-make -f Makefile.windows

Thanks dude
