### ISSUE TITLE
cannot find -lopencv110

### ISSUE THREAD

**Issue by czxichen** [chai2010/opencv#6]
D:/gcc/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv110
collect2.exe: error: ld returned 1 exit status

**Comment by chai2010** [comment]
need run `go generate` first:

1. `go get -d github.com/chai2010/opencv`
2. `go generate` and `go install`

**Comment by czxichen** [comment]
恩呢,解决了,谢谢
